"use client";
import "../global.css";
import Footer from "./Components/Footer";
import Topbar from "./Components/Topbar";
import "bootstrap/dist/css/bootstrap.min.css";
import { Roboto } from "next/font/google";

export const metadata = {
  title: "HerodesJosue",
  description: "Generated by Next.js",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Topbar />
        <div className="backgroundImg">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
