import "../global.css";
import Footer from "./Components/Footer";
import Topbar from "./Components/Topbar";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "HerodesJosue",
  description: "Generated by Next.js",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        <div className="backgroundImg">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
